server:
    port: ${SERVER_PORT:8082}

feign:
    client:
        config:
            default:
                connectTimeout: 60000
                readTimeout: 10000
    rest:
        eventosfull:
            name: eventosfull
            url: http://localhost:8080
            auth:
                client: eventos-api
                secret: "iuhew*!n&298SUI#ds"

        auth:
            name: auth
            url: http://localhost:8081