# Configurações basicas
spring:
  main.banner-mode: 'OFF'
  application:
    name: eventosfull

server:
  max-http-request-header-size: 10MB
  servlet:
    context-path: /

info:
  app:
    name: EventosFull
    description: Projeto final da disciplina de Arquitetura de Software
    version: ${project.version}
management:
  endpoints:
    # enabled-by-default: false
    web:
      exposure:
        include: health,info
---

# Database.
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:eventosfull}
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

---

#swagger
spring:
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /documentation.html

client:
  credentials:
    - client: eventos-api
      secret: "iuhew*!n&298SUI#ds"
    - client: inscricoes-api
      secret: "din2$#(34f&230*_DKLW"
    - client: emails-api
      secret: "oi&c*3xs_23-D$@3sar04"
